[[redirects]]
  from = "/signnow/*"
  to = "https://realistic-factor-gw.aws-usw2.cloud-ara.tyk.io/signnow/:splat"
  status = 200

[[redirects]]
  from = "/ethers/*"
  to = "https://testnet.bscscan.com/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "https://x8ki-letl-twmt.n7.xano.io/api:3xJ2zQ1y/:splat"
  status = 200
