export enum RouteNames {
    AccountLogin = 'AccountLogin',
    Dashboard = 'Dashboard',
    TokenTable = 'TokenTable',
    Fundraising = 'Fundraising',
    TokenTableTokenAllocation = 'TokenTableTokenAllocation',
    TokenTableUnlockTokens = 'TokenTableUnlockTokens',
    FundraisingRound = 'FundraisingRound',
    FundraisingRoundCreate = 'FundraisingRoundCreate',
    FundraisingRoundEdit = 'FundraisingRoundEdit',
    FundraisingRoundInvestors = 'FundraisingRoundInvestors',
    ProjectEdit = 'ProjectEdit',
    DocumentUpload = 'DocumentUpload',
    Tasks = 'Tasks',
    Portfolio = 'Portfolio',
}
